name: Self-Test Caller

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  call-reusable-workflow:
    # In a real project, this would be:
    # uses: SamuelMarks/c-ci/.github/workflows/c-cmake-ci.yml@master
    uses: ./.github/workflows/c-cmake-ci.yml
    with:
      build_type: 'Release'
      cmake_configure_flags: '-DC_CDD_BUILD_TESTING=ON -DC_ORM_BUILD_TESTING=ON -DC_ABSTRACT_HTTP_BUILD_TESTING=ON -DC_FS_BUILD_TESTING=ON -DBUILD_TESTING=ON'
